version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
    groups:
      all-go:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/cmd/echo-gateway"
    schedule:
      interval: daily
      time: "01:00"
  - package-ecosystem: "docker"
    directory: "/cmd/gateway-registry"
    schedule:
      interval: daily
      time: "01:00"
  - package-ecosystem: "docker"
    directory: "/cmd/ohttprelay"
    schedule:
      interval: daily
      time: "01:00"
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"

